classdef Config
% Catches a mistyped settings block before anything is energised.

methods (Static)

    function check(cfg)
    % Catches a mistyped config block before anything is energised.

        mustBeOneOf(cfg.Run, ...
            ["plan" "board" "ramp" "wiper" "k3" "verify" "ohms" "meters" ...
             "sweep"], "RUN");

        if cfg.RampSteps < 2 || cfg.RampSteps > 769
            error("PVLoad:BadRampSteps", ...
                "RAMP_STEPS is %g. The sweep has 769 states and a ramp needs " + ...
                "at least 2 of them.", cfg.RampSteps);
        end
        if cfg.RampDwell <= 0
            error("PVLoad:BadRampDwell", "RAMP_DWELL must be positive.");
        end
        if cfg.OhmsSettle <= 0
            error("PVLoad:BadOhmsSettle", "OHMS_SETTLE must be positive.");
        end
        if isempty(cfg.WiperCodes) || any(cfg.WiperCodes < 0) || ...
           any(cfg.WiperCodes > 2 * cfg.WiperSteps) || ...
           any(mod(cfg.WiperCodes, 1) ~= 0)
            error("PVLoad:BadWiperCodes", ...
                "WIPER_CODES must be whole numbers from 0 to %d, which is the " + ...
                "range of a FULL code sum.", 2 * cfg.WiperSteps);
        end

        A = cfg.Adapt;
        if A.Enabled
            if A.CoarseStep < 1 || A.CoarseStep > cfg.WiperSteps || ...
               mod(A.CoarseStep, 1) ~= 0
                error("PVLoad:BadAdaptStep", ...
                    "ADAPT_COARSE_STEP is %g. It thins by wiper code the way " + ...
                    "CODE_STEP does, so it must be a whole number from 1 to " + ...
                    "%d.", A.CoarseStep, cfg.WiperSteps);
            end
            if A.Gap <= 0 || A.Gap > 1 || A.Bend <= 0 || A.Bend > 1
                error("PVLoad:BadAdaptThreshold", ...
                    "ADAPT_GAP and ADAPT_BEND are fractions of the measured " + ...
                    "I-V span, above 0 and at most 1. They are %g and %g.", ...
                    A.Gap, A.Bend);
            end
            nCoarse = numel(0:A.CoarseStep:cfg.WiperSteps) + ...
                      numel(0:A.CoarseStep:2 * cfg.WiperSteps) + ...
                      cfg.IncludeShort + cfg.IncludeOpen;
            if A.MaxPoints < nCoarse
                error("PVLoad:BadAdaptCap", ...
                    "ADAPT_MAX_POINTS is %g and the coarse pass alone is %d " + ...
                    "states. The cap has to hold at least the coarse pass.", ...
                    A.MaxPoints, nCoarse);
            end
            if A.MaxRounds < 1 || mod(A.MaxRounds, 1) ~= 0
                error("PVLoad:BadAdaptRounds", ...
                    "ADAPT_MAX_ROUNDS is %g. It must be a whole number of at " + ...
                    "least 1.", A.MaxRounds);
            end
        end

        D = cfg.Dmm;
        if D.Enabled && D.V.Address == D.I.Address
            error("PVLoad:MeterAddressConflict", ...
                "Both meters are set to %s. They need separate addresses.", ...
                D.V.Address);
        end
        if D.Enabled && D.Timeout <= max(D.V.Conversion, D.I.Conversion)
            error("PVLoad:MeterTimeoutTooShort", ...
                "DMM_TIMEOUT is %g s but one conversion takes %g s.", ...
                D.Timeout, max(D.V.Conversion, D.I.Conversion));
        end
        % Checked per meter, and not gated on D.Enabled, for the same reason
        % DMM_R_RANGE is not: RUN "ohms" opens one meter and configures it
        % through the same path. An NPLC the meter does not have is rejected at
        % the bus with nothing to say which of these two numbers caused it.
        Meter.checkNplc(D.V, D.LineHz);
        Meter.checkNplc(D.I, D.LineHz);
        Meter.checkNplc(D.R, D.LineHz);

        if D.Enabled && D.V.Range > 0
            % Every range is named, so one that does not exist is a config
            % error here rather than something the meter sorts out later. A
            % zero means the range is sized from VOC_FULL or ISC_FULL instead,
            % which is what keeps one configuration working on any of them.
            Meter.checkRange(D.V.Range, D.V.Ranges, "DMM_V_RANGE", D.V.Label);
        end
        if D.Enabled && D.I.Range > 0
            Meter.checkRange(D.I.Range, D.I.Ranges, "DMM_I_RANGE", D.I.Label);
        end
        % Not gated on D.Enabled: RUN "ohms" uses one meter and that flag is
        % about the pair the sweep needs.
        if D.R.Range > 0
            Meter.checkRange(D.R.Range, D.R.Ranges, "DMM_R_RANGE", D.R.Label);
        end
        if D.Enabled && cfg.Cell.VocFull > max([D.V.Range, max(D.V.Ranges)])
            error("PVLoad:VocAboveMeterRange", ...
                "VOC_FULL is %g V and the highest volts range the %s has is " + ...
                "%g V, so the OPEN point would overflow.", ...
                cfg.Cell.VocFull, D.V.Label, max(D.V.Ranges));
        end
        if D.Enabled && D.V.Range > 0 && cfg.Cell.VocFull > D.V.Range
            error("PVLoad:VocAboveMeterRange", ...
                "VOC_FULL is %g V but DMM_V_RANGE is %g V, so the OPEN point " + ...
                "would overflow. Set it to 0 to size the range from VOC_FULL.", ...
                cfg.Cell.VocFull, D.V.Range);
        end
        if D.Enabled && cfg.Cell.IscFull > max(D.I.Ranges)
            error("PVLoad:IscAboveMeterRange", ...
                "ISC_FULL is %g A and the %s stops at %g A. Nothing in the " + ...
                "instrument goes higher, so the cell has to be measured " + ...
                "through a shunt or under weaker light.", ...
                cfg.Cell.IscFull, D.I.Label, max(D.I.Ranges));
        end
        if D.Enabled && cfg.Cell.IscFull > 0 && ...
           cfg.Cell.IscFull < 0.001 * min(D.I.Ranges)
            warning("PVLoad:IscFarBelowMeterRange", ...
                "ISC_FULL is %g A and the lowest amps range the %s has is " + ...
                "%g A, so the current reading is the bottom of a range. A " + ...
                "6.5 digit DMM is not an electrometer.", ...
                cfg.Cell.IscFull, D.I.Label, min(D.I.Ranges));
        end
    end

end
end


function mustBeOneOf(value, allowed, name)
    if ~any(string(value) == allowed)
        error("PVLoad:BadOption", "%s must be one of %s, not ""%s"".", ...
            name, strjoin("""" + allowed + """", ", "), string(value));
    end
end
