classdef Profiles

methods (Static)

function list = all(nplc, lineHz, zeroCorrect)

    list = {ddc196(), scpi34401A(nplc, lineHz, zeroCorrect)};
end

function profile = select(profiles, model, name)

    for k = 1:numel(profiles)
        if profiles{k}.Model == model
            profile = profiles{k};
            return
        end
    end

    known = strings(1, numel(profiles));
    for k = 1:numel(profiles)
        known(k) = """" + profiles{k}.Model + """";
    end
    error("PVLoad:BadMeterModel", ...
        "%s is ""%s"". It must be one of %s.", ...
        name, model, strjoin(known, ", "));
end

function s = spec(profile, address, range, ranges, zeroCorrect, timeout)

    s = struct( ...
        'Ddc',         profile, ...
        'Address',     address, ...
        'Model',       profile.Model, ...
        'Label',       profile.Label, ...
        'Conversion',  profile.Conversion, ...
        'ZeroCorrect', zeroCorrect, ...
        'Timeout',     timeout, ...
        'Range',       range, ...
        'Ranges',      ranges, ...
        'Port',        []);
end

end
end

function p = ddc196()
% Every letter is off manual 196-901-01 Rev D: functions 3.9.2, ranges
% table 3-9, the rest table 3-8. Amps is F3, not F1 or F2 which are AC.
% S3 is 6.5 digits and 106 ms. K2 is EOI on and hold-off off, which is
% what lets the other meter be triggered while this one converts.
% Prefixes are figure 3-6; DC amps is DCI, not DCA. StatusMap is where
% each setting sits in the U0 word, mapped on the bench.

    p = struct( ...
        'Model',      "196", ...
        'Label',      "Keithley 196", ...
        'Dialect',    "ddc", ...
        'ReadTerm',   "CR/LF", ...
        'WriteTerm',  "LF", ...
        'IdPrefix',   "196", ...
        'Volts',      "F0", ...
        'Amps',       "F3", ...
        'Ohms',       "F2", ...
        'Range',      "R%d", ...
        'AutoRange',  "R0", ...
        'RangeOnly',  "R%d", ...
        'Prefixes',   "DCV|ACV|OHM|OCO|DCI|ACI|dBV|dBI", ...
        'StatusMap',  struct('F', 3, 'K', 6, 'R', 18, 'S', 19, 'T', 20, 'Z', 27), ...
        'Common',     "Z0B0G0M0K2S3T5", ...
        'Machine',    "U0", ...
        'Error',      "U1", ...
        'Conversion', 0.106, ...
        'VRanges',    [0.3 3 30 300], ...
        'IRanges',    [3e-4 3e-3 3e-2 3e-1 3], ...
        'RRanges',    [300 3e3 3e4 3e5 3e6 3e7 3e8]);
end

function p = scpi34401A(nplc, lineHz, zeroCorrect)
% Manual 34401-90004. Not run against the instrument yet.
%
% TRIG:DEL:AUTO ON, not TRIG:DEL AUTO: AUTO is a node, and the short
% form comes back -224. Conversion is nplc line cycles plus ~60 ms,
% doubled under autozero.

    p = struct( ...
        'Model',      "34401A", ...
        'Label',      "Agilent 34401A", ...
        'Dialect',    "scpi", ...
        'ReadTerm',   "LF", ...
        'WriteTerm',  "LF", ...
        'IdPrefix',   "34401A", ...
        'Volts',      "VOLT:DC", ...
        'Amps',       "CURR:DC", ...
        'Ohms',       "RES", ...
        'AutoRange',  "RANG:AUTO ON", ...
        'RangeOnly',  "%s:RANG %g", ...
        'Common',     ["TRIG:SOUR IMM", "TRIG:DEL:AUTO ON", ...
                       "TRIG:COUN 1", "SAMP:COUN 1"], ...
        'AutoZero',   "ZERO:AUTO %s", ...
        'HighZ',      "INP:IMP:AUTO ON", ...
        'Nplc',       nplc, ...
        'Clear',      "*CLS", ...
        'Trigger',    "INIT", ...
        'Fetch',      "FETC?", ...
        'Read',       "READ?", ...
        'Machine',    "*IDN?", ...
        'Error',      "SYST:ERR?", ...
        'NoError',    "+0", ...
        'Overflow',   9.8e37, ...
        'Conversion', 0.06 + (1 + double(zeroCorrect)) * nplc / lineHz, ...
        'VRanges',    [0.1 1 10 100 1000], ...
        'IRanges',    [0.01 0.1 1 3], ...
        'RRanges',    [100 1e3 1e4 1e5 1e6 1e7 1e8]);
end
